### PR TITLE
Real

### PR DESCRIPTION
**Pull request by NotClavilux**

### CODE REVIEW

**Comment by Blitzedzz** [comment]
real

**Review by Blitzedzz — CHANGES_REQUESTED** [review]
its already 0.1.8 
also what did you change in index.html

**Comment by NotClavilux** [comment]
i added toast notifications when injected etc trust

**Comment by Blitzedzz** [comment]
oh ok!

**Comment by NotClavilux** [comment]
forgot to try

**Comment by Blitzedzz** [comment]
Ok!

**Comment by Blitzedzz** [comment]
also why did the interface change?

**Pull request merged**
